#!/usr/bin/env python
import time
start_time = time.time()

import itertools
combs=[]
a = range(1,5)
b = len(a)
combs = list(itertools.permutations(a, b))

def test_set(mone,mtwo,mtre,set):
    sets = int(''.join(map(str,set)))
    mlier = int(''.join(map(str,mone)))
    mand = int(''.join(map(str,mtwo)))
    prod = int(''.join(map(str,mtre)))
    if mlier * mand == prod:
        if sets == int(''.join(map(str,[mlier,mand,prod]))):
            print sets
            print mlier, mand, prod
            return True

def iter_set(set):
    mone = []
    mtwo = []
    mthr = []
    print "=========="
    print set
    print "=========="
    for n in range(0,len(set)-2):
        for o in range(n,len(set)-1):
            print set[n]



for set in combs:
    iter_set(set)
#    if test_set(set[0],set[1],set[2]):
#        print set

print("--- %s seconds ---" % (time.time() - start_time))
